name = "beacon-cm"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"
id = ""				# 填入你的 KV 命名空间 ID

[[d1_databases]]
binding = "DB"
database_name = "beacon-users"
database_id = ""			# 填入你的 D1 数据库 ID